server:
  port: 8081

spring:
  application:
    name: monitoring-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/condominio_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:4z/J3r/4X8A/4eM/B4b/C4e/D4f/E4g/F4h/G4i/H4j/I4k/J4l/K4m/L4n/M4o=}
